# -*- coding: utf-8 -*-
"""Question 2 - 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPVOJVrH9zcJdGL4A1vl9bjI7EJ9YPcW
"""

from math_function import add


def main():

    data_1 = int(input("masukkan input 1 :"))
    data_2 = int(input("masukkan input 2 :"))
    operator = input("masukkan operator :")

    if operator == "+":
        result = add(data_1, data_2)

    print("{} {} {} = {} ".format(data_1, operator, data_2, result))


if __name__ == "__main__":
    print("Hello Main !")
    main()