# -*- coding: utf-8 -*-
"""Question 2-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XF2rhkkLWtPK8z80GNXPlct1oBKmmgdv
"""

def add(a, b):
    return a + b